# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5166ec6e8b3625d69845aec4a2b032cdd2e6e786ba2dd795f5f2bf534a27e2fc2c850e034dadfc8e52dd7a5b6f0c19c090967ffa8c90660bf48fbcd3f8f7057d
  rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

test:
  secret_key_base: 12363a2806226d0a3acc781b1735a5f69eaff5010d34a6cc3e764359e35b4a15bd918fa47382e6f95a06a9876613e52242a1c51cec3a1615a05a70f346d89763

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rakuten_application_id: <%= ENV["RAKUTEN_APPLICATION_ID"] %>
  rakuten_affiliate_id: <%= ENV["RAKUTEN_AFFILIATE_ID"] %>

